#!/bin/sh
set -e

echo "[pre-commit] Running prettier..."
npx prettier --write 'src/**/*.ts'
git add -u 'src/**/*.ts'

echo "[pre-commit] Running eslint..."
npx eslint 'src/**/*.ts'

echo "[pre-commit] All checks passed."
